categories = ['business','entertainment','general','health','science','sports','technology']

supported_countries = [("Argentina","ar"),("Greece", "gr"),("Netherlands","nl"),("South Africa","za"),("Australia","au"),("Hong Kong","hk"),("New Zealand","nz"),("South Korea","kr")
                       ,("Austria","at"),("Hungary","hu"),("Nigeria","ng"),("Sweden","se"),("Belgium","be"),("India","in")
                       ,("Norway","no"),("Switzerland","ch"),("Brazil","br"),("Indonesia","id"),("Philippines","ph"),("Taiwan","tw"),
                       ("Bulgaria","bg"),
                       ("Ireland","ie"),
                       ("Poland","pl"),
                       ("Thailand","th"),
                       ("Canada","ca"),
                       ("Israel","il"),
                       ("Portugal","pt"),
                       ("Turkey","tr"),
                       ("China","cn"),
                       ("Italy","it"),
                       ("Romania","ro"),
                       ("UAE","ae"),
                       ("Colombia","co"),
                       ("Japan","jp"),
                       ("Russia","ru"),
                       ("Ukraine","ua"),
                       ("Cuba","cu"),
                       ("Latvia","lv"),
                       ("Saudi Arabia","sa"),
                       ("United Kingdom","gb"),
                       ("Czech Republic","cz"),
                       ("Lithuania","lt"),
                       ("Serbia","rs"),
                       ("United States","us"),
                       ("Egypt","eg"),
                       ("Malaysia","my"),
                       ("Signapore","sg"),
                       ("Venezuela","ve"),
                       ("France","fr"),
                       ("Mexico","mx"),
                       ("Slovakia","sk"),
                       ("Germany","de"),
                       ("Morocco","ma"),
                       ("Slovenia","si")]
